#include "cutfhe++.h"

namespace cuTFHEpp {
    EXPLICIT_LVL_DOWN_DEFINE(CUTFHEPP_KEY_SWITCH);

    EXPLICIT_LVL_UP_DEFINE(CUTFHEPP_GATE_BOOTSTRAPPING_TLWE2TLWEFFT);
    EXPLICIT_LVL_DOWN_UP_DEFINE(CUTFHEPP_GATE_BOOTSTRAPPING);

    EXPLICIT_LVL_UP_DEFINE(CUTFHEPP_PROG_BOOTSTRAPPING_TLWE2TLWEFFT);
    EXPLICIT_LVL_DOWN_UP_DEFINE(CUTFHEPP_PROG_BOOTSTRAPPING);
    EXPLICIT_LVL_DEFINE(CUTFHEPP_GenLUT);
    EXPLICIT_LVL_DEFINE(CUTFHEPP_GenDLUT);
    EXPLICIT_LVL_DEFINE(CUTFHEPP_GenDLUTP);

    EXPLICIT_LVL_DEFINE(CUTFHEPP_MU_POLYGEN);
    EXPLICIT_LVL_DEFINE(CUTFHEPP_LUT_POLYGEN);

    EXPLICIT_LVL_DEFINE(CUTFHEPP_HOMADD_PLAIN);
    EXPLICIT_LVL_DEFINE(CUTFHEPP_HOMADD);

    EXPLICIT_LVL_DEFINE(CUTFHEPP_HOMSUBLSHIFT);
    EXPLICIT_LVL_DEFINE(CUTFHEPP_HOMSUB);
    EXPLICIT_LVL_DEFINE(CUTFHEPP_HOMSUBSingle);

    EXPLICIT_LVL_DEFINE(CUTFHEPP_HOMNOT);

    EXPLICIT_LVL_DEFINE(CUTFHEPP_HOMLSHIFT);

    EXPLICIT_LVL_DEFINE(CUTFHEPP_HOMCOPY);
}
